# Generated by Django 5.2.5 on 2025-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='conteudo_completo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
