# Generated by Django 4.2.14 on 2025-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_categoria_noticia_conteudo_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='feed_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
