# Generated by Django 5.2.5 on 2025-08-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20250821_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='feed_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(),
        ),
    ]
