# Generated by Django 5.2.5 on 2025-08-27 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lucaquestion',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='question',
            field=models.TextField(verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Sessão'),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='lucaquestion',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token único para confirmação de e-mail', null=True, unique=True, verbose_name='Token de Confirmação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(help_text='Número do WhatsApp com formato (11) 99999-9999', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato esperado: (11) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='questions_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
